### ISSUE TITLE
Release securedrop-workstation-dom0-config 1.0.0

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-workstation#1103]
- RM: @legoktm 
- Deputy RM: @zenmonkeykstop 
- Comms: TK 
- QA: (all-team)

## QA:
To test this release, you will need a dedicated computer compatible with Qubes 4.2. You'll also need a test SecureDrop server instance, either:
- [a production hardware instance](https://docs.securedrop.org/en/stable/admin/installation/installation_overview.html),
- [a staging or production virtualized test enviroment](https://developers.securedrop.org/en/latest/virtual_environments.html#),
- or (as a fallback) [a server dev environment with Tor services enabled ](https://developers.securedrop.org/en/latest/setup_development.html)(`make dev-tor`)

> Do not use a production server instance to test release candidates! You'll need to copy the SVS's Submission Private Key to the SecureDrop Workstation config, and it will have access to submissions, so you should use test  instances and test data only.

In order to configure SecureDrop Workstation, you'll need the Journalist interface address and authorization key, and the Submission Private Key from the server instance - so set the server instance up first.

Next,  install Qubes 4.2 (preferably the latest stable patch version) on your Qubes computer. Then install SecureDrop Workstation, following the standard installation process with 2 deviations:
- Instead of downloading the latest production RPM from yum.securedrop.org, download the latest f37 release candidate RPM from yum-test.securdrop.org
- When updating `config.json`, set the value of `environment` to `staging` instead of prod - this will enforce the use of the test repos and latest RCs for both workstation and client packages.

Once the installation is complete, copy the `securedrop-workstation` source tagged with the curent RC version  to `dom0` on your test system using [`make clone`](https://developers.securedrop.org/en/latest/workstation_development.html#manually-updating-dom0-code) and run the configuration tests in dom0 with `make test`.

Then, add a column with your config and initial test results (installation, setup, dom0 tests) in the [SecureDrop Workstation QA Matrix](https://docs.google.com/spreadsheets/d/1u3mhMeLxbArzIwsqfqFx8T9eRhTcXx1pGNJV4UvktU4/edit?gid=526478650#gid=526478650), and complete one or more acceptance test scenarios (check with the release manager if you're unsure as to which ones are needed), and complete any linked release-specific tests, copying the scenario test plans from the linked wiki pages, and adding the completed versions as comments on this issue.

(Then take a rest and get yourself a nice treat - you've earned it.)
### QA test plan:
Note: there is no upgrade scenario because all users must reinstall for this release.

### Fresh install (prodlike install)
Qubes ~4.2.1~ [edit: 4.2.2-rc1 or newer] expected, please note hardware
#### Testing:
- [ ] download rpm from https://yum-test.securedrop.org/workstation/dom0/f37/, copy into dom0 and install (see steps at https://workstation.securedrop.org/en/stable/admin/install.html#download-and-install-securedrop-workstation but it's OK to skip the download through dnf and signature verification parts)
- [ ] RPM installs successfully in dom0
- [ ] Set up `/usr/share/securedrop-workstation-dom0-config/`, see https://workstation.securedrop.org/en/stable/admin/install.html#configure-securedrop-workstation-estimated-wait-time-60-90-minutes, make sure that in config.json, environment is set to `staging`.
- [ ] Run `sdw-admin --validate && sdw-admin --apply`; both should finish successfully.
- [ ] open a terminal in one of the SDW appVMs/templates, run `dpkg -l | grep securedrop` and verify you have 0.11.0-rc1 packages
- [ ] After running the updater, `~/.securedrop_updater/sdw-last-updated` has been updated. (verifies https://github.com/freedomofpress/securedrop-workstation/issues/1107)
- [ ] Manually start the `sdw-notify` systemd user unit after running the updater - you should not see a notification popup (verifies https://github.com/freedomofpress/securedrop-workstation/issues/1107)
- [ ] Open the menu, for sd-devices you should see "Files" and "Disks". for sd-whonix you should see "Anon Connection Wizard" and "Tor Control panel" (verifies https://github.com/freedomofpress/securedrop-workstation/issues/1109)
- [ ] basic client functionality requiring Tor (login, first sync) completed successfully.
- [ ] Run through selected sscenarios from [SecureDrop Workstation QA Matrix](https://docs.google.com/spreadsheets/d/1u3mhMeLxbArzIwsqfqFx8T9eRhTcXx1pGNJV4UvktU4/edit?gid=526478650#gid=526478650)
### RC1:
- [x] [In release branch] bump rc version using `update_version` script, update changelog in .spec file and markdown: https://github.com/freedomofpress/securedrop-workstation/pull/1102
- [x] [In release branch] create rc tag 
- [x] build rc, commit build logs, and publish artifact to yum-test

### RC2:
- [x] [In release branch] bump rc version using `update_version` script, update changelog in .spec file and markdown: https://github.com/freedomofpress/securedrop-workstation/pull/1102
- [x] [In release branch] create rc tag 
- [x] build rc, commit build logs, and publish artifact to yum-test

### Release:
- [ ] [In release branch] Bump version via `update_version` script, and update changelog in .spec file and markdown
- [ ] [In release branch]  Create prod tag (signed by release signing key)
- [ ] Build prod artifact, sign with release key, commit build logs
- [ ] QA/smoketest of prod artifact (stuff rpm in dom0 of SDW prod machine)
- [ ] Publish prod artifact to yum repo

### Post-release
- [ ] Backport version and changelog updates to main branch from release branch
- [ ] Retro if/as needed
- [ ] Update documentation

**Comment by rocodes** [comment]
### testing
version: rc1
status: WIP
- [x] download rpm from https://yum-test.securedrop.org/workstation/dom0/f37/, copy into dom0 and install (see steps at https://workstation.securedrop.org/en/stable/admin/install.html#download-and-install-securedrop-workstation but it's OK to skip the download through dnf and signature verification parts)
- [x] RPM installs successfully in dom0
- [x] Set up /usr/share/securedrop-workstation-dom0-config/, see https://workstation.securedrop.org/en/stable/admin/install.html#configure-securedrop-workstation-estimated-wait-time-60-90-minutes, make sure that in config.json, environment is set to staging.
- [x] Run sdw-admin --validate && sdw-admin --apply; both should finish successfully.
- [x] open a terminal in one of the SDW appVMs/templates, run dpkg -l | grep securedrop and verify you have 0.11.0-rc1 packages 
- [ ] basic client functionality requiring Tor (login, first sync) completed successfully. (todo)
- [ ] Run through https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-Acceptance-Tests and other QA testing (todo)

**Comment by legoktm** [comment]
#### Testing:
* rc2
* T490, Qubes 4.2.1

- [x] download rpm from https://yum-test.securedrop.org/workstation/dom0/f37/, copy into dom0 and install (see steps at https://workstation.securedrop.org/en/stable/admin/install.html#download-and-install-securedrop-workstation but it's OK to skip the download through dnf and signature verification parts)
- [x] RPM installs successfully in dom0
- [x] Set up `/usr/share/securedrop-workstation-dom0-config/`, see https://workstation.securedrop.org/en/stable/admin/install.html#configure-securedrop-workstation-estimated-wait-time-60-90-minutes, make sure that in config.json, environment is set to `staging`.
- [x] Run `sdw-admin --validate && sdw-admin --apply`; both should finish successfully.
- [x] open a terminal in one of the SDW appVMs/templates, run `dpkg -l | grep securedrop` and verify you have 0.11.0-rc1 packages
- [ ] basic client functionality requiring Tor (login, first sync) completed successfully.
- [ ] Run through https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-Acceptance-Tests and other QA testing
- [x] After running the updater, `~/.securedrop_updater/sdw-last-updated` has been updated. (verifies https://github.com/freedomofpress/securedrop-workstation/issues/1107)
- [x] Manually start the `sdw-notify` systemd user unit after running the updater - you should not see a notification popup (verifies https://github.com/freedomofpress/securedrop-workstation/issues/1107)
- [x] Open the menu, for sd-devices you should see "Files" and "Disks". for sd-whonix you should see "Anon Connection Wizard" and "Tor Control panel" (verifies https://github.com/freedomofpress/securedrop-workstation/issues/1109)

**Comment by cfm** [comment]
Smoke-testing done; detailed QA scenarios to follow next week.

* `securedrop-workstation-dom0-config` `1.0.0-rc2`
* Qubes ~~4.2.1~~ `4.2.2-rc1`
* ThinkPad T14

#### Testing:
- [x] download rpm from https://yum-test.securedrop.org/workstation/dom0/f37/, copy into dom0 and install (see steps at https://workstation.securedrop.org/en/stable/admin/install.html#download-and-install-securedrop-workstation but it's OK to skip the download through dnf and signature verification parts)
- [x] RPM installs successfully in dom0
- [x] Set up `/usr/share/securedrop-workstation-dom0-config/`, see https://workstation.securedrop.org/en/stable/admin/install.html#configure-securedrop-workstation-estimated-wait-time-60-90-minutes, make sure that in config.json, environment is set to `staging`.
- [x] Run `sdw-admin --validate && sdw-admin --apply`; both should finish successfully.
- [x] open a terminal in one of the SDW appVMs/templates, run `dpkg -l | grep securedrop` and verify you have 0.11.0-rc1 packages
- [x] basic client functionality requiring Tor (login, first sync) completed successfully.
- [ ] Run through https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-Acceptance-Tests and other QA testing
- [x] After running the updater, `~/.securedrop_updater/sdw-last-updated` has been updated. (verifies https://github.com/freedomofpress/securedrop-workstation/issues/1107)
- [x] Manually start the `sdw-notify` systemd user unit after running the updater - you should not see a notification popup (verifies https://github.com/freedomofpress/securedrop-workstation/issues/1107)
- [x] Open the menu, for sd-devices you should see "Files" and "Disks". for sd-whonix you should see "Anon Connection Wizard" and "Tor Control panel" (verifies https://github.com/freedomofpress/securedrop-workstation/issues/1109)

**Comment by rocodes** [comment]
@deeplow can you provide more details about the export failures please, eg STR / where the process failed/what error message or error logs you see?

**Comment by rocodes** [comment]
Thanks @deeplow - For creating a device, we ask people to follow https://workstation.securedrop.org/en/stable/admin/provisioning_usb.html , so as long as you're using that or equivalent workflow and creating a whole-encrypted device, or a device with one encrypted partition (other non encrypted partitions are fine), any STR / bugreports are useful

**Comment by rocodes** [comment]
#### Setup
**hw:** T480 / Qubes 4.2.2-rc1 
**version** 1.0.0-rc2 
#### Testing (WIP, will update as I go)
- [x] download rpm from https://yum-test.securedrop.org/workstation/dom0/f37/, copy into dom0 and install (see steps at https://workstation.securedrop.org/en/stable/admin/install.html#download-and-install-securedrop-workstation but it's OK to skip the download through dnf and signature verification parts)
- [x] RPM installs successfully in dom0
- [x] Set up `/usr/share/securedrop-workstation-dom0-config/`, see https://workstation.securedrop.org/en/stable/admin/install.html#configure-securedrop-workstation-estimated-wait-time-60-90-minutes, make sure that in config.json, environment is set to `staging`.
- [x] Run `sdw-admin --validate && sdw-admin --apply`; both should finish successfully.
- [ ] open a terminal in one of the SDW appVMs/templates, run `dpkg -l | grep securedrop` and verify you have 0.11.0-rc1 packages
- [ ] basic client functionality requiring Tor (login, first sync) completed successfully.
- [ ] Run through https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-Acceptance-Tests and other QA testing
- [ ] After running the updater, `~/.securedrop_updater/sdw-last-updated` has been updated. (verifies https://github.com/freedomofpress/securedrop-workstation/issues/1107)
- [ ] Manually start the `sdw-notify` systemd user unit after running the updater - you should not see a notification popup (verifies https://github.com/freedomofpress/securedrop-workstation/issues/1107)
- [ ] Open the menu, for sd-devices you should see "Files" and "Disks". for sd-whonix you should see "Anon Connection Wizard" and "Tor Control panel" (verifies https://github.com/freedomofpress/securedrop-workstation/issues/1109)

**Comment by rocodes** [comment]
Looks like https://github.com/freedomofpress/securedrop-client/issues/1926, same question - I'm curious about the logs in sd-devices, specifically the export_status, when that happens.

It's definitely something to fix, but I'm not sure where it ranks in our priorities - if the user pulls out a drive mid-export they can/should expect that to fail.

**Comment by rocodes** [comment]
@deeplow (and other testers) re the export scenarios:
* Devices are still locked every time an export finishes. 
* If a user manually unlocks the drive beforehand (eg via the commandline or the file browser app in sd-devices), they will not be re-prompted for the drive password. But the drive will still lock after export is finished.
* There is an open issue for providing the option to keep a drive unlocked (https://github.com/freedomofpress/securedrop-client/issues/1729), which would be easy to implement now, but it has not been implemented yet.

HTH!

**Comment by rocodes** [comment]
I still have to finish up some of the export/print test plan, but with the addition of https://github.com/freedomofpress/securedrop-client/pull/2102 in sd-app, basic print testing so far is looking good on both supported HP and Brother printers. Basic export testing is also looking good and I will test https://github.com/freedomofpress/securedrop-client/pull/2100 tomorrow to mark for review since I think it will resolve some of the corner case issues with error reporting. 

until tm :)

**Comment by rocodes** [comment]
Qubes: 4.2.2-rc2
dom0 config: rc2 
client: 0.11.0 -rc1 + print changes (0.11.0-rc2 equiv)
   
##### Export

- When **Export** is first clicked on a submission:
  - [x] the "Preparing to export..." message is displayed
  - [x] the `sd-devices` VM is started
  - [x] the user is prompted to insert an Export USB
  - [x] On clicking **Cancel**, the prompt closes and the file is not exported
- When **Export** is clicked on the submission again:
  - [x] the "Preparing to export..." message is displayed
  - [x] the user is prompted to insert an Export USB
  - When the user inserts an invalid Export USB, attaches it to the sd-devices VM and clicks **Next**:
    - x ] a message is displayed indicating that the Export USB is invalid and
    the user is prompted to insert a valid device
- When **Export** is clicked on the submission again:
  - [x] the "Preparing to export..." message is displayed
  - [x] the user is prompted to insert an Export USB
  - When the user inserts a valid Export USB, attaches it to the sd-devices VM, and clicks **Next**:
    - [x] the user is prompted for the Export USB's password if the (LUKS) device is locked
    - [x] the user is not prompted for the USB's password, if the (LUKS or VeraCrypt) device is unlocked
    - [x] the user is not prompted for the USB's password, if the (LUKS or VeraCrypt) device is unlocked and mounted
  - When the user enters an invalid Export USB password and clicks **Next**:
    - [x] a failure message is displayed and the user is prompted to enter the password again
  - When the user enters an valid Export USB password and clicks **Next**:
    - [x] the file is saved to the Export USB and a success message is shown
  - When the user encounters error state(s) during export:
    - [x] a user-facing message (rather than an `EXPORT_ERROR_CODE` style message) is shown  (yes, except see discussion above and https://github.com/freedomofpress/securedrop-client/issues/2098)
- When the user detaches the Export USB and mounts it on another VM or computer:
  - [x] the decrypted submission(s) is available in on the Export USB, in a directory `sd-export-<timestamp>/export_data`

##### Print
Tested with HP LaserJetPro 4001dn and Brother HL-L2360DW

- When the user clicks **Print** on a downloaded submission:
  - [x] a "Preparing to print..." message is displayed
  - [x] the `sd-devices` VM is started
  - [x] the user is prompted to connect a supported printer
- When the user connects a printer, attaches it to the `sd-devices` VM, and clicks **Continue**:
  - [ ] a "Printing..." message is displayed: No, "preparing to print" and then the xpp panel closes, but this is expected
  - [x] the X Printer Panel dialog is displayed with the printer selected
- When the user clicks **Print** in the X Printer Panel:
  - [x] the submission is printed successfully.
- [x] A multi-page document can be printed successfully  (todo: will try some more filetypes eg multifile pdf)

**Comment by zenmonkeykstop** [comment]
### Fresh install (prodlike install)
Qubes  4.2.2-rc1, Novacustom NV41

#### Testing:
- [x] download rpm from https://yum-test.securedrop.org/workstation/dom0/f37/, copy into dom0 and install (see steps at https://workstation.securedrop.org/en/stable/admin/install.html#download-and-install-securedrop-workstation but it's OK to skip the download through dnf and signature verification parts)
- [x] RPM installs successfully in dom0
- [x] Set up `/usr/share/securedrop-workstation-dom0-config/`, see https://workstation.securedrop.org/en/stable/admin/install.html#configure-securedrop-workstation-estimated-wait-time-60-90-minutes, make sure that in config.json, environment is set to `staging`.
- [x] Run `sdw-admin --validate && sdw-admin --apply`; both should finish successfully.
- [x] open a terminal in one of the SDW appVMs/templates, run `dpkg -l | grep securedrop` and verify you have 0.11.0-rc1 packages
- [x] After running the updater, `~/.securedrop_updater/sdw-last-updated` has been updated. (verifies https://github.com/freedomofpress/securedrop-workstation/issues/1107)
- [ ] ~Manually start the `sdw-notify` systemd user unit after running the updater - you should not see a notification popup (verifies https://github.com/freedomofpress/securedrop-workstation/issues/1107)~ **skipped**
- [x] Open the menu, for sd-devices you should see "Files" and "Disks". for sd-whonix you should see "Anon Connection Wizard" and "Tor Control panel" (verifies https://github.com/freedomofpress/securedrop-workstation/issues/1109)
- [x] basic client functionality requiring Tor (login, first sync) completed successfully.
- [ ] Run through selected scenarios from [SecureDrop Workstation QA Matrix](https://docs.google.com/spreadsheets/d/1u3mhMeLxbArzIwsqfqFx8T9eRhTcXx1pGNJV4UvktU4/edit?gid=526478650#gid=526478650) **Large dataset in progress**

**Comment by rocodes** [comment]
#### Environment 
Qubes 4.2.2-rc1 / T480 / staging servers

#### Candidate(s)
dom0 rc3 / client rc2

#### Installation
upgrade (rc{1,2} -> rc{2,3}) via updater  

- [x] SDW prompts to apply updates
- [x] Upgrade completed without error and prompted dom0 reboot
- [x] Synced with 500 messages
- [x] Printed multi-page PDF with lots of metadata and embedded images successfully on both HP (4001dn) and Brother (HL-L2360DW), pages appear clean and without any garbled metadata/headers 
- [x] Successful LUKS and VeraCrypt exports in various conditions, printer acceptance testing in various conditions (Attempting to print with no printer connected yields "connect printer" prompt, and connecting allows user to proceed with printing (autoattach) works)
    
I was able, once, to encounter a printer error, when deliberately trying to print without a printer connected, but I couldn't replicate it.

**Comment by rocodes** [comment]
## prod qa instructions:

- Fresh install Qubes 4.2.2-rc1 (soon to be 4.2.2, like possibly later today, so check back)
- Treat this (almost) like a prod install, so follow the docs at workstation.securedrop.org like an end-user would, but instead of downloading the RPM from yum.securedrop.org, download from yum-qa.securedrop.org. 
- After installing the RPM but before running `apply`, manually edit the following file so that the repo URLs point to our prod qa repos:
- `/srv/salt/securedrop_salt/sd-default.config.yml` : change the prod settings (`dom0_yum_repo_url`) to `https://yum-qa.securedrop.org/workstation/dom0`
- You should not have to change the build flavour/type in config.json - it should say "prod".  (If it doesn't, file an issue!)
- `apply`
- Your packages should be signed with the prod key, your laptop should behave like a prod laptop (power settings, lid close handling settings).  Please follow the public-facing documentation, QA with prod settings in mind, and treat any discrepancies as issues that need to be resolved  :)

**Comment by legoktm** [comment]
For apt-qa, I also copied `/srv/salt/securedrop_salt/apt_freedom_press.sources.j2` to `/srv/salt/securedrop_salt/apt-qa_freedom_press.sources.j2`, and edited the path in `/srv/salt/securedrop_salt/sd-default.config.yml`. Otherwise when the securedrop-keyring package is installed, it overwrites our apt->apt-qa.

**Comment by rocodes** [comment]
@deeplow : Yes, and we should update the developer docs as well
