### ISSUE TITLE
Release SecureDrop Workstation 1.1.0

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-workstation#1209]
## Description
Release [SecureDrop Workstation 1.1.0](https://github.com/freedomofpress/securedrop-workstation/milestone/8), with Fedora 41 support and other bugfixes and improvements.
Note: keyring bootstrap package support has been deferred til [1.2.0], so reopening this ticket. (https://github.com/freedomofpress/securedrop-workstation/milestone/11).

- RM and Deputy RM: @rocodes + @deeplow pairing 
- Comms: @rocodes @nathandyer 
- additional QA: @nathandyer 

### Pre-release tasks
- [ ] Update docs with f40 -> f41 , update Qubes install docs to reference 4.2.4 : https://github.com/freedomofpress/securedrop-workstation-docs/pull/304

### QA / Test plan
Testers, please choose one of Clean install or Upgrade. Instructions: 
https://github.com/freedomofpress/securedrop-workstation/wiki/QA-Testing#dom0-testing-securedrop-workstation-dom0-config

#### Clean Install (Qubes 4.2.4)
Follow Clean install (RC) setup instructions.
- [ ] Install completes successfully (#1159)
- [ ] Ensure sd-viewer has libreoffice installed (#1162)
- [ ] Basic regression testing: VMs boot, basic functionality, send-receive-decrypt-export (one tester total)
- [ ] Rest of test plan (below)

#### Upgrade (no f41 template present)
Follow Upgrade (RC) setup instructions. Do not install fedora-41-xfce template before upgrading.
- [ ] fedora-41-xfce not present before upgrade
- [ ] Upgrade completes successfully using updater (#1165) - check updater detail log and dom0 journal, ensure no errors 
- [ ] Basic regression testing: VMs boot, basic functionality, send-receive-decrypt-export (one tester total)
- [ ] Rest of test plan (below)

#### Upgrade B: f41 template already present (@rocodes)
- [ ] Same as test plan above, I'll do this one
- [ ] rest of test plan

#### 1.1.0 test plan (start in dom0)
**Key validation**
In dom0 `/usr/share/securedrop-workstation-dom0-config`, test the following validation conditions for `sd-journalist.sec` by running `sdw-admin --validate` and observing the output. #1205
- [ ] Missing private key (sd-journalist.sec) fails validation
- [ ] Pubkey instead of private key fails validation (test with eg `sudo sed -i "s/PRIVATE/PUBLIC/g" /usr/share/securedrop-workstation-dom0-config/sd-journalist.sec`) and a message that it's not a private key
- [ ] Password-protected private key fails validation and yields descriptive error message (you may want to generate a keypair outside dom0 in an environment with pinentry, password-protect the key, then copy into dom0)

**VM config**
- [ ] Visible in Qubes Menu (`APPS` tab): `sd-app`, `sd-gpg` (#1191, #1216, #1237, #1219, #1237)
- [ ] `qvm-prefs sd-proxy provides_network` is `False` (#1146)

**systemd units**
Observe <img height="22px" src="https://github.com/user-attachments/assets/73bec9fc-82a1-4d6c-b845-4e2ff2703e1d"/> when running each (#1088):
- [ ] `systemctl --user status sdw-notify.timer`
- [ ] `systemctl --user status securedrop-user-xfce-icon-size`
- [ ] `systemctl --user status securedrop-user-xfce-settings`

**Fedora 41 bump**
- Examine output of `qvm-ls | grep fedora-41-xfce`: (#1221)
- [ ] `fedora-41-xfce` is present (TemplateVM), fedora-41-xfce-dvm is template for `sys-net`, `sys-firewall`
- [ ] `sd-fedora-41-dvm` exists and has `fedora-41-xfce` template; sd-fedora-41-dvm is `sys-usb` template
- [ ] `qvm-check --quiet sd-fedora-40-dvm || echo "Not installed"` shows "Not installed"
 
**Correct packages**
- `qvm-run --pass-io sd-base-bookworm-template 'apt list --installed | grep securedrop'` (#1161)
  - [ ] `securedrop-workstation-config` is present
  - [ ] `securedrop-workstation-grsec` is present

**late sd-log setup** (https://github.com/freedomofpress/securedrop-workstation/pull/1253)

Open terminal in `sd-log`:
   - [ ] and type `ls ~/QubesIncomingLogs/`. Various `sd-*` qubes should be listed
   - [ ] type `tail -f ~/QubesIncomingLogs/sd-proxy/syslog.log`
- [ ] open terminal in `sd-proxy` and type `sudo journalctl -f`
- [ ] on sd-proxy, open another teminal (to cause something to show in the systemctl journal)
- [ ] Compare the output of the log in `sd-log` and in `sd-proxy`. They should be approximately the same.

<details><summary>Example of what it should look like:</summary>

![Image](https://github.com/user-attachments/assets/e4672130-193c-409e-88de-dadd4e8f2ad0)

</details>

**Uninstall** (optional/one tester)
`sdw-admin --uninstall` then reboot or reload systemd daemon (sudo systemctl daemon-reload).
- [ ] securedrop-related systemd units (user and system) are all removed. On the following dom0 commands it should show "... could not be found":
- [ ] `systemctl --user status sdw-notify.timer` 
- [ ] `systemctl --user status securedrop-user-xfce-icon-size`
- [ ] `systemctl --user status securedrop-user-xfce-settings`
----

<details> <summary>Excluded from QA</summary>

#### Dev-facing
- Enable and fix tests that weren't running  #1090
- docs(readme): link to contribution guidelines #1177 
- Bump the dependencies group across 1 directory with 5 updates #1182 
- Verify PGP key embedded in .sources files are correct #1183 
- Actually test that logs are flowing to sd-log #1087 
- Test that apt interprets our .sources files correctly #1093 
- Remove perl from tests #1184 
- Automatically log into the client application #1188
- Bump the dependencies group across 1 directory with 8 updates #1220 
- Lint our GitHub Actions workflows with zizmor #1222 
- Bump the dependencies group across 1 directory with 5 updates #1228 
- Use script to capture rpm build log #1241 

#### Due to test coverage
- Remove unecessary nopat kernelopt #1172 
- Set vm template consistently across Salt files; cleanup unused requisites #1226 

</details>

### Release
See https://developers.securedrop.org/en/latest/workstation_release_management.html#release-an-rpm-package
- [ ] Check if any security fixes need to be pulled in
- [ ] Create `release/1.1.0` branch
- [ ] On release branch, update version and changelog, create rc tag
- [ ] Build and reproduce RC packages, open PR on yum-test
- [ ] merge yum-test PR, start RC QA (test plan tk)
- [ ] Prod changelog, version bump, and prod-signed tag
- [ ] Prod packages on yum-qa: open (draft) PR to `release` branch
- [ ] Pre-release QA (yum-prod review checklist can be stepped through without approving/merging)
- [ ] Go/no-go meeting, finalize comms roles and timeline
- [ ] Deploy 
- [ ] Comms (blog post), docs update, socials
- [ ] Backport + close release issue

**Comment by rocodes** [comment]
(https://github.com/freedomofpress/securedrop-workstation/issues/1230 dupe but more detailed)

**Comment by nathandyer** [comment]
### QA / Test plan
Testers, please choose one of Clean install or Upgrade. Instructions: 
https://github.com/freedomofpress/securedrop-workstation/wiki/QA-Testing#dom0-testing-securedrop-workstation-dom0-config

#### Upgrade (no f41 template present) **IN PROGRESS**
Follow Upgrade (RC) setup instructions. Do not install fedora-41-xfce template before upgrading.
- [ ] fedora-41-xfce not present before upgrade
- [ ] Upgrade completes successfully using updater (#1165) - check updater detail log and dom0 journal, ensure no errors 
- [ ] Basic regression testing: VMs boot, basic functionality, send-receive-decrypt-export (one tester total)
- [ ] Rest of test plan (below)


#### 1.1.0 test plan (start in dom0)
**Key validation**
In dom0 `/usr/share/securedrop-workstation-dom0-config`, test the following validation conditions for `sd-journalist.sec` by running `sdw-admin --validate` and observing the output. #1205
- [ ] Missing private key (sd-journalist.sec) fails validation
- [ ] Pubkey instead of private key fails validation (test with eg `sudo sed -i "s/PRIVATE/PUBLIC/g" /usr/share/securedrop-workstation-dom0-config/sd-journalist.sec`) and a message that it's not a private key
- [ ] Password-protected private key fails validation and yields descriptive error message (you may want to generate a keypair outside dom0 in an environment with pinentry, password-protect the key, then copy into dom0)

**VM config**
- [ ] Visible in Qubes Menu (`APPS` tab): `sd-app`, `sd-gpg`, `sd-viewer` (#1191, #1216, #1237, #1219, #1237)
- [ ] Visible in Qubes Menu (`SERVICE` tab): `sd-proxy` (#1146)
- [ ] Qubes Menu -> `sd-proxy` -> settings: provides network is unchecked (#1146)

**systemd units**
Observe <img height="22px" src="https://github.com/user-attachments/assets/73bec9fc-82a1-4d6c-b845-4e2ff2703e1d"/> when running each (#1088):
- [ ] `systemctl --user status sdw-notify.timer`
- [ ] `systemctl --user status securedrop-user-xfce-icon-size`
- [ ] `systemctl --user status securedrop-user-xfce-settings`

**Fedora 41 bump**
- Examine output of `qvm-ls | grep fedora-41-xfce`: (#1221)
- [ ] `fedora-41-xfce` is present (TemplateVM), is template for `sys-usb`, `sys-net`, `sys-firewall`
- [ ] `sd-fedora-41-dvm` exists and has `fedora-41-xfce` template available
- [ ] `qvm-check --quiet sd-fedora-40-dvm || echo "Not installed"` shows "Not installed"
 
**Correct packages**
- `qvm-run --pass-io sd-base-bookworm-template 'apt list --installed | grep securedrop'` (#1161)
  - [ ] `securedrop-workstation-config` is present
  - [ ] `securedrop-workstation-grsec` is present

**Uninstall** (optional/one tester)
`sdw-admin --uninstall` then reboot or reload systemd daemon (sudo systemctl daemon-reload).
- [ ] securedrop-related systemd units (user and system) are all removed. On the following dom0 commands it should show "... could not be found":
- [ ] `systemctl --user status sdw-notify.timer` 
- [ ] `systemctl --user status securedrop-user-xfce-icon-size`
- [ ] `systemctl --user status securedrop-user-xfce-settings`
----

<details> <summary>Excluded from QA</summary>

#### Dev-facing
- Enable and fix tests that weren't running  #1090
- docs(readme): link to contribution guidelines #1177 
- Bump the dependencies group across 1 directory with 5 updates #1182 
- Verify PGP key embedded in .sources files are correct #1183 
- Actually test that logs are flowing to sd-log #1087 
- Test that apt interprets our .sources files correctly #1093 
- Remove perl from tests #1184 
- Automatically log into the client application #1188
- Bump the dependencies group across 1 directory with 8 updates #1220 
- Lint our GitHub Actions workflows with zizmor #1222 
- Bump the dependencies group across 1 directory with 5 updates #1228 
- Use script to capture rpm build log #1241 

#### Due to test coverage
- Remove unecessary nopat kernelopt #1172 
- Set vm template consistently across Salt files; cleanup unused requisites #1226 

</details>

**Comment by rocodes** [comment]
@nathandyer Thank you for your testing, and apologies - those were errors in the test plan not in your results. I have amended the test plan to clarify a couple cases (sd-viewer and sd-proxy are still internal, so other testers will do `qvm-prefs` for them rather than searching in the app menu).

Your test run LGTM. I will provide some additional test coverage.

**Comment by rocodes** [comment]
> > I have amended the test plan to clarify a couple cases (sd-viewer and sd-proxy are still internal, so other testers will do qvm-prefs for them rather than searching in the app menu);
> 
> I may have wrongly assumed we were testing using staging while on `yum-test`, but according to this, they should not be marked as internal. Perhaps I should have noted in the test plan that this will only be visible when testing on `yum-qa`.

Right, good point; I think though that we shouldn't have a different test plan for prod vs yum-test. (I guess this argues against the conditional "sometimes internal sometimes not" logic more than anything tbh)

**Comment by rocodes** [comment]
(neglected to post my QA results yesterday, but I went through QA on the "upgrade / f41 templates already installed" scenario. Successful provisioning run, confirmed basic assurances (correctly updated fedora templates, correct vm properties, autoattach rules in sys-usb). 

We have proceeded to prod tag + artifact building and will update when time for pre-release QA.

**Comment by rocodes** [comment]
Prod qa packages are live on yum-qa. Testers, please ensure that if you are testing the "Upgrade - no fedora 41 templates" test plan, you do not have the fedora-41-xfce template installed before you start QA. QA environment setup instructions are in the wiki page linked in the issue body.

(My results: clean install successful - didn't QA just did a provisioning run. Upgrade in progress.)

**Comment by rocodes** [comment]
We are superseding 1.1.0 with a hotfix release, 1.1.1, due to an issue uncovered in pre-release QA with the updater.

Testers, please follow this amended test plan:
- [ ] Start with a production setup flipped to the yum-qa repos, as described in "pre-release qa" in this guide: https://github.com/freedomofpress/securedrop-workstation/wiki/QA-Testing#dom0-testing-securedrop-workstation-dom0-config.  Instead of just `dnf download`, you may have to specify version 1.0.2 to download.  If upgrade path: reboot your machine once you have provisioned. If clean install: just download the rpm and install in dom0.
- [ ] Be sure that, if you QA'd previously, you do not have the log file `/var/log/qubes/update-fedora-41-xfce.log` owned by root in place. (You may remove this file.) 
- [ ] At least one tester: please test from a machine that does not have fedora-41-xfce template preinstalled.  
- [ ] **If upgrade path**: Run the updater. Updater completes successfully.  **If clean install path**: provision. Provisioning completes successfully. 
- [ ] Run the updater a second time (sdw-updater --skip-delta 0), or run the qubes GUI updater selecting fedora-41-xfce. Updates complete successfully.

**Comment by nathandyer** [comment]
Just completed a successful clean install QA run on 1.1.1:

- [x] Start with a production setup flipped to the yum-qa repos, as described in "pre-release qa" in this guide: https://github.com/freedomofpress/securedrop-workstation/wiki/QA-Testing#dom0-testing-securedrop-workstation-dom0-config.  Instead of just `dnf download`, you may have to specify version 1.0.2 to download.  If upgrade path: reboot your machine once you have provisioned. If clean install: just download the 1.1.1 rpm and install in dom0.
- [ ] Be sure that, if you QA'd previously, you do not have the log file `/var/log/qubes/update-fedora-41-xfce.log` owned by root in place. (You may remove this file.)  (NA, clean install)
- [ ] At least one tester: please test from a machine that does not have fedora-41-xfce template preinstalled.  (NA, started from Qubes 2.4.2 with fedora-41-xfce installed and set to default template)
- [ ] **If upgrade path**: Run the updater. Updater completes successfully.  **If clean install path**: provision. Provisioning completes successfully.  (NA)
- [x] Flip back to yum-qa repos in `srv/salt` and `sd-default-config.yml` again, following the wiki QA setup instructions. 🙃  
- [x] Run the updater a second time (sdw-updater --skip-delta 0), or run the qubes GUI updater selecting fedora-41-xfce. Updates complete successfully.

+ Basic smoke tests. LGTM!

**Comment by zenmonkeykstop** [comment]
- [x] Start with a production setup flipped to the yum-qa repos, as described in "pre-release qa" in this guide: https://github.com/freedomofpress/securedrop-workstation/wiki/QA-Testing#dom0-testing-securedrop-workstation-dom0-config.  Instead of just `dnf download`, you may have to specify version 1.0.2 to download.  If upgrade path: reboot your machine once you have provisioned. If clean install: just download the 1.1.1 rpm and install in dom0.
- [x] Be sure that, if you QA'd previously, you do not have the log file `/var/log/qubes/update-fedora-41-xfce.log` owned by root in place. (You may remove this file.) 
- [x] At least one tester: please test from a machine that does not have fedora-41-xfce template preinstalled. **CONFIRMED**
- [x] **If upgrade path**: Run the updater. Updater completes successfully.  **If clean install path**: provision. Provisioning completes successfully. 
- [x] Flip back to yum-qa repos in `srv/salt` and `sd-default-config.yml` again, following the wiki QA setup instructions. 🙃  
- [x] Run the updater a second time (sdw-updater --skip-delta 0), or run the qubes GUI updater selecting fedora-41-xfce. Updates complete successfully.
