### ISSUE TITLE
Create Debian and RPM packages for workstation components

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#167]
We will use Debian packages (for templateVMs) and RPM (for dom0) as the primary way to provision/update workstation code and its dependencies. As such, we need to create and maintain packages for all key components.

At this time, packaging tasks are tracked in the specific repo the package if for, if applicable, or in this repository otherwise.

- [x] securedrop-client package - https://github.com/freedomofpress/securedrop-client/issues/22
- [X] securedrop-proxy package - https://github.com/freedomofpress/securedrop-proxy/issues/6
- [x] securedrop-workstation-config (specifies package dependencies for base template; provides baseline configuration and hardening) - #164
- [x]  securedrop-workstation-grsec  (tracks latest kernel for base template and specifies kernel-related dependencies) - #165
- [x] securedrop-svs-disp-config (specifies package dependencies for disposable VMs for viewing documents) - #182
- [x] RPM for `qubes-template-securedrop-workstation` for installation in dom0 - #157
- [x] RPM template and configuration package(s) for dom0 - #171

**Comment by redshiftzero** [comment]
RPMs not making it into alpha, moving to beta

**Comment by eloquence** [comment]
The basic Debian and RPM packaging work is done.

Work towards nightly builds of Debian packages is tracked here: 
https://github.com/freedomofpress/securedrop-debian-packaging/issues/8

The release process for Debian packages is documented in the repo's README:
https://github.com/freedomofpress/securedrop-debian-packaging/

Analog work for RPM packaging will be tracked separately. It will likely not be prioritized until the Debian packaging work is done, given that client development is moving at a much faster pace than configuration and provisioning, hence greater immediate payback from build automation. 

That closes out this epic. :tada:
