### ISSUE TITLE
Replace pre-alpha workflow with alpha client

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#179]
Once the following dependencies are met, we should replace the pre-alpha workflow with the alpha client:
- [x] Download and decrypt messages - https://github.com/freedomofpress/securedrop-client/issues/40
- [x] Decrypt downloaded documents - https://github.com/freedomofpress/securedrop-client/issues/66
- [x] View downloaded documents - https://github.com/freedomofpress/securedrop-client/issues/20
- [x] Create updated client package - https://github.com/freedomofpress/securedrop-client/issues/22

Stretch for MVP integration:
~~Replies to sources - https://github.com/freedomofpress/securedrop-client/issues/16~~

We will need the `securedrop-client` package to be updated and delete existing code for the pre-alpha workflow, update the README, etc. 

~~As part of this work, we should convert `sd-journalist` to `sd-proxy` (https://github.com/freedomofpress/securedrop-workstation/issues/138).~~ (let's do as a separate issue)

This will enable us to QA on master with the most important client functionality. Deletion (https://github.com/freedomofpress/securedrop-client/issues/18) can be handled as an iteration.
