### ISSUE TITLE
Basic print/export support

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#290]
For the beta, we want to support two ways of moving documents off the SecureDrop Workstation:

- export to a storage medium attached to a USB port
- print to a supported printer

This involves a lot of work across the workstation repos. This epic tracks all **must-have** issues to provide basic print/export support.

## Shared concerns

- [x] Consider renaming VMs for clarity - #285
- [x] Package export code - #271

## Export

- [x] Finalize high level export approach - #84
- [x] Create proof-of-concept implementation - #259
 - [x] (UX) Complete UX design for basic export workflow - https://github.com/freedomofpress/securedrop-ux/issues/57
- [x] Finalize metadata format for exports - #280
- [x] Return USB device state details as part of export attempts - #264 
- [x] Implement pre-flight checks - #281
- [ ] Handle filename conflicts - #270
- [x] (Client) Implement basic export workflow - https://github.com/freedomofpress/securedrop-client/issues/21
- [ ] (Stretch) Detect disk space availability prior to export - #292

## Print
- [x] Create proof-of-concept print workflow - #267
- [x] (UX) Complete UX design for basic print workflow - https://github.com/freedomofpress/securedrop-ux/issues/63
- [ ] Return printer job status to client
- [x] Add support for common HP laser printer
- [ ] Select final print front-end - #294
- [ ] Ensure all supported file formats are printable - #295
- [x] (Client) Implement basic print workflow - https://github.com/freedomofpress/securedrop-client/issues/477
- [ ] Decide whether we should support user-installed printers (in sd-export, the DispVM template) instead of relying on fully unattended printer setup (which limits compatibility)

**Comment by eloquence** [comment]
We've delivered the core functionality we need for the pilot and there are several other follow-up tweaks not tracked in this epic, so it serves limited organizing purpose at this point. Closing, but note that several of the issues cross-referenced from here are still relevant, and we'll want to prioritize them for future iterations.
