### ISSUE TITLE
Switch templates and packages to Debian Buster

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#306]
We want to switch all Debian-based VM templates and workstation packages to Debian Buster, without the complexity of supporting two Debian releases at the same time. This breaks down as follows:

## Completed

- [x] Attempt to run securedrop-client on Debian Buster - https://github.com/freedomofpress/securedrop-client/issues/528
- [x] Test version of securedrop-workstation template with Buster and grsec - #308
- [x] Update FPF's PyPI index - https://github.com/freedomofpress/securedrop-debian-packaging/pull/86
- [x] Update build requirements for Buster packages - https://github.com/freedomofpress/securedrop-debian-packaging/pull/85
- [x] Add support for securedrop-export Debian Buster tests - https://github.com/freedomofpress/securedrop-export/issues/24

## 11/20-12/4 sprint
- [x] Make updates to package build logic for client/proxy/export builds - https://github.com/freedomofpress/securedrop-debian-packaging/issues/88, https://github.com/freedomofpress/securedrop-debian-packaging/issues/91, https://github.com/freedomofpress/securedrop-debian-packaging/issues/92
- [x] Add Buster builds to CI - https://github.com/freedomofpress/securedrop-client/issues/527, https://github.com/freedomofpress/securedrop-proxy/issues/50, https://github.com/freedomofpress/securedrop-export/issues/30
- [x] Start creating nightly Buster builds - https://github.com/freedomofpress/securedrop-debian-packaging/issues/76
- [x] Upload Buster-based RPM - #344
- [x] Switch securedrop-workstation template to Buster #345 

## 12/5-12/18 sprint

- [ ] Switch to Whonix 15 (which is also Stretch->Buster) - #300

**Comment by eloquence** [comment]
Updated epic per discussions at sprint planning today. Need a bit more discussion/scoping around the goals for updating the package build logic (e.g., is it acceptable to break stretch builds, and if so, when will we cross that line?).

**Comment by eloquence** [comment]
(Keeping epic on the backlog, but we should be able to fully close this out in the 11/20-12/4 sprint.)

**Comment by eloquence** [comment]
Closing as all tasks in epic were completed and `make all` should now result in a Buster-based SDW; feel free to reopen if there are follow-up tasks that should be tracked in this epic. :)

**Comment by conorsch** [comment]
#300 still outstanding, but we're in the home stretch! :smiley:
