### ISSUE TITLE
SecureDrop Workstation 0.2.3-rpm/0.2.2-deb QA

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#494]
This issue tracks QA reports for
- [0.2.2 release of Debian packages](https://github.com/freedomofpress/securedrop-debian-packaging/releases/tag/0.2.2)
- [0.2.3 release of RPM package](https://github.com/freedomofpress/securedrop-debian-packaging/releases/tag/0.2.4)

Following this test plan:
https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-Beta-Acceptance-Tests

Reports for the previous release can be found here:
#484

**Comment by eloquence** [comment]
Self-assigning to the following scenarios from the test plan:
1. Client scenarios. Scenario: Online mode _except print_ as I do not have a supported printer.
2. Scenario: Client and Journalist Interface both in use

**Comment by eloquence** [comment]
#### Login

- [x] when SecureDrop desktop icon is double-clicked, preflight updater is displayed
- [x] After preflight updater runs, when user clicks **Continue**, login dialog is displayed
- In login dialog:
  - [x] show/hide password functionality works
  - [x] incorrect password cannot log in
  - [x] invalid 2FA token cannot log in
  - [x] 2FA token reuse cannot log in after password failure
  - [x] valid credentials and 2FA can log in

**Comment by eloquence** [comment]
#### Sources

- after valid login:
  - [x] the login dialog closes
  - [x] source data is downloaded and source list is populated
  - [x] user is prompted for GPG key access
  - [x] submissions and replies are decrypted
  - [x] the source list is displayed but no sources are selected by default
  - [x] the conversation view is not populated
- when a source is selected in source list:
  - [x] conversation view is populated with source conversation 
  - [x] a source message containing HTML is displayed as unformatted text
  - [x] source submissions have an active **Download** button
  - [x] source submission compressed file size is displayed accurately --- :x: BUT: note that _uncompressed_ size is not, see https://github.com/freedomofpress/securedrop-client/issues/917

**Comment by eloquence** [comment]
- when the upper right 3-dot button is clicked:
  - [x] a menu is displayed with a **delete source account** option
  - when **delete source account** is selected:
    - [x] the source is deleted from the source list and the conversation view is blanked
    - [x] the source is deleted from the server and not restored on next sync
    - [x] source submissions and messages are removed from the client's data directory
- when a source is starred in source list, and the client is closed and reopened in Online mode:
  - [x] the source is still starred in the source list

**Comment by eloquence** [comment]
#### Replies

- when a source is selected in the source list:
  - [x] the reply panel is available for use and there is no message asking the user to sign in
  - [x] a reply can be added to the conversations
  - [x] a reply containing HTML is displayed as unformatted text
  - [x] two replies added immediately after each other are ordered correctly

#### Submissions

##### Preview

- when **Download** is clicked on a submission:
  - [x] the submission is downloaded and decrypted
  - [x] the Download button is replaced with **Print** and **Export** options
  - [x] the submission filename is displayed.
- For a DOC submission:
   - [x] when the submission filename is clicked, a disposable VM (dispVM) is started.
   - [x] after the dispVM starts, the submission is displayed in LibreOffice
   - [x] when LibreOffice is closed, the dispVM shuts down
- For a PDF submission:
   - [x] when the submission filename is clicked, a dispVM is started.
   - [x] after the dispVM starts, the submission is displayed in evince
   - [x] when evince is closed, the dispVM shuts down
- For a JPEG submission:
   - [x] when the submission filename is clicked, a dispVM is started.
   - [x] after the dispVM starts, the submission is displayed in Image Viewer
   - [x] when evince is closed, the dispVM shuts down

**Comment by eloquence** [comment]
- When **Export** is first clicked on a submission:
  - [x] the "Preparing to export..." message is displayed
  - [x] the `sd-devices` VM is started
  - [x] the user is prompted to insert an Export USB (after pressing Continue)
  - [x] On clicking **Cancel**, the prompt closes and the file is not exported
- When **Export** is clicked on the submission again:
  - [x] the "Preparing to export..." message is displayed
  - [x] the user is prompted to insert an Export USB
  - When the user inserts an invalid Export USB, attaches it to the sd-devices VM and clicks **OK**:
    - [x] a message is displayed indicating that the Export USB is invalid and
    the user is prompted to insert a valid device
- When **Export** is clicked on the submission again:
  - [x] the "Preparing to export..." message is displayed
  - [x] the user is prompted to insert an Export USB
  - When the user inserts a valid Export USB, attaches it to the sd-devices VM, and clicks **OK**:
    - [x] the user is prompted for the Export USB's password 
  - When the user enters an invalid Export USB password and clicks **Submit**:
    - [x] a failure message is displayed and the user is prompted to enter the password again  - :x: Note broken dialog behavior if user interacts with any other windows while typing password, logged in https://github.com/freedomofpress/securedrop-client/issues/826#issuecomment-597931820
  - When the user enters a valid Export USB password and clicks **Submit**:
    - [x] the file is saved to the Export USB
- When the user detaches the Export USB and mounts it on another VM or computer:
  - [x] the decrypted submission is available in on the Export USB, in a directory `sd-export-<timestamp>/export_data`

**Comment by eloquence** [comment]
### Scenario: Client and Journalist Interface both in use

> **Note:** this scenario requires access to the *Journalist Interface* (JI) via 
> Tor Browser. If the scenario is being tested on Qubes, the JI address can be found
> in `sd-whonix` in `/usr/local/etc/torrc.d/50_user.conf`. The `sd-proxy` VM includes
> Tor Browser, and can be used to access the JI without config changes.

> **Prerequisites:**
> 
> - server is available and contains source test data
> - client data directory is empty

#### Login

- [ ] when SecureDrop desktop icon is double-clicked, preflight updater is displayed *(updates skipped)*
- [ ] After preflight updater runs, when user clicks **Continue**, login dialog is displayed *(updates skipped)*
- after valid login to client:
  - [x] the login dialog closes
  - [x] source data is downloaded and source list is populated
  - [ ] user is prompted for GPG key access *(skipped due to previous grant)*
  - [x] submissions and replies are decrypted
  - [x] the source list is displayed but no sources are selected by default
  - [x] the conversation view is not populated
- when the JI address is visited in Tor Browser:
  - [x] JI login page is displayed
- after valid login to JI using same account as for client:
  - [x] sources page is displayed, containing the same sources as the client (order may differ)

#### Sources, replies, submissions

- when a source is starred in the client:
  - [x] the source is also starred in the JI after a page reload
- when a starred source is unstarred in the JI:
  - [ ] the source is also unstarred in the client after next sync. :x: This build still has https://github.com/freedomofpress/securedrop-client/issues/888
- when a reply is sent to a source via the client:
 - [x] the reply is visible in the JI and can be viewed by the source in the Source Interface
- when a reply is sent to a source via the JI:
  - [x] the reply is visible in the source conversation view after next sync **(actually immediately & then transitions to sent, test plan should be clarified)**
- when an individual file submission is deleted in the JI:
  - [ ] the submission is no longer listed in the conversation view  :x:

OK, this is where things still fall apart. I observed three different behaviors:

1) For a single file that had not been downloaded in client yet (and subsequently deleted in JI) it was properly removed from the list.

2) For one file out of a batch of files that _had_ been downloaded in client (and subsequently deleted in JI), I got this glitch:
![broken-file](https://user-images.githubusercontent.com/213636/76478420-df0b7a80-63c5-11ea-88f9-678f84c0fe0f.png)

3) Going back to the source from 1) and submitting/deleting another file _without_ downloading it in the client resulted in this error:

`sqlalchemy.orm.exc.NoResultFound: No row was found for one()` ([full traceback](https://gist.github.com/eloquence/699b886c35773e75ea3dfb896a4a7e55))

**Comment by emkll** [comment]
I will be working on the following scenarios:
* Scenario: Offline mode without existing data
* Scenario: Offline mode with existing data

**Comment by eloquence** [comment]
1. Updates to RPMs of existing installs worked without a hitch, didn't verify whether _all_ changes were successfully applied.
2. `uninstall` command worked just fine as well, it did throw a few warnings at the end about trying to delete files that didn't exist. I didn't capture those but will see if it happens again next time.
3. So far so good on another prod install, will be testing with that setup tomorrow.

**Comment by emkll** [comment]
### Scenario: Offline mode with existing data

#### Offline to Online

- [x] When SecureDrop desktop icon is double-clicked, preflight updater is displayed
- [x] After preflight updater runs, when user clicks **Continue**, login dialog is displayed
- [x] When user clicks **Work Offline**, login dialog closes and main window opens
- after startup:
  - [x] there is no sync attempt with the server
  - [x] the source list is populated with contents of last server sync
- When the user selects a source with submissions from the source list:
  - [x] the conversation view is populated with the source conversation
  - [x] the reply panel is inactive, with a "Sign in" message
  - [x] a previously downloaded submission can be exported 
  - [x] a previously downloaded submission can be printed
  - [x] When the user clicks **Download** on an undownloaded submission, a message is displayed instructing the user to sign in to perform the download
- When the user clicks the top-left user icon and chooses **Sign in**:
  - [x] the login dialog is displayed over the main window
- When the user enters valid login details and clicks **Log in**:
  - [x] the login dialog closes
  - [x] The user icon is updated to reflect the user's details
  - [x] source data is synced with the server
- When the user selects a source with submissions from the source list:
  - [x] the conversation view is populated with the source conversation
  - [x] the reply panel is active
  - [x] When the user replies to a source, the reply is added to the source conversation
  - [x] When the user clicks **Download** on an undownloaded submission, the submission is downloaded and decrypted
  - [x]  When the user clicks **Export** on a submission, the export process can be completed
  - [x]  When the user clicks **Print** on a submission, the print process can be completed
- When the user clicks the main window close button:
  - [x] the client exits. (:exclamation: note, the main window close button does not exit if the export dialog)

**Comment by eloquence** [comment]
- when an individual message is deleted in the JI:
  - [ ] the message is no longer listed in the conversation view :x: a similar glitch as with deleted files, see below.
  - [x] the messages are deleted from the client database

When deleting an individual message via the JI, the message is not removed from the conversation view - instead it jumps up vertically, next to a reply, so you end up with this (the message "Talk to me" was deleted via the JI):
![overlaping-content](https://user-images.githubusercontent.com/213636/76669351-7d274e00-6548-11ea-95ed-2b541c5ae0a4.png)

The message is correctly removed from the DB and therefore gone after a restart.

**Comment by eloquence** [comment]
- when a source is deleted in the JI:
  - [x] the source is no longer listed in the client after next sync
  - [ ] files associated with the source are no longer present in the  client data directory :x: files can still be found in the client data directory, same behavior as described in https://github.com/freedomofpress/securedrop-client/issues/892
- when a source is deleted in the client:
  - [x] the source is no longer listed in the JI after a page reload

**Comment by emkll** [comment]
### Mime handing test ( in progress)

:exclamation: we run `qvm-open-in-vm` without the `--view-only` parameter, which means that edits in the DispVM are sent back to `sd-app`. Is there a UX reason for this? If not, I think we should add `--view-only` (we do it for the export archive)
#### Verify mime handling in sd-app
- [X] Behavior in client (e.g. mailto, http:// link w/ modified client that disables escaping)
http links are opened with the open-in-dvm-desktop, but error when calling `/usr/bin/open-in-vm` because it expects a file. This provides defense-in-depth and sufficient mitigations
- [x] Review default mime handler apps in sd-app, tested manually but also automated tests now available in https://github.com/freedomofpress/securedrop-workstation/pull/472

#### Verify mime handling in `sd-viewer`
- [x] Review default mime handler apps in `sd-viewer`
Tested manually but also automated tests in https://github.com/freedomofpress/securedrop-workstation/pull/472
- [ ] Send a .desktop file that execute code, see what happens
- [x] Check macro execution default policy in libreoffice

**Comment by eloquence** [comment]
Next round of QA here: #499
