### ISSUE TITLE
Release SecureDrop Workstation 0.5.1

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#643]
The next version of the SecureDrop Workstation will enforce the use of fedora-32 as the default for sys-* VMs due to its EOL. This  issue tracks this and any other release-critical issues, the QA process, and the release itself.

- [x] Land fedora-32 support (#627) 
- [x] Update changelog
- [x] Create test plan
- [x] Prepare test package for `yum-test`
- [x] Complete QA
- [x] Production release and comms

**Comment by conorsch** [comment]
Added a test plan here: https://github.com/freedomofpress/securedrop-workstation/wiki/0.5.1-Test-Plan

Given that F32 has received upstream fixes to resolve the salt breakage, upgrades are now possible via the GUI updater.

**Comment by eloquence** [comment]
Went through a fresh install attempt today; provisioning failed due to #644 (see output in https://gist.github.com/eloquence/d29ba85df5153e9d09c328db3a6d00b4). Will reset to clean slate and retry after fix lands in apt-test.

**Comment by zenmonkeykstop** [comment]
Ran through upgrade testing, successfully with no issues:

### Scenario: in-place upgrade

- Install prod 0.5.0 on dedicated hardware
- Clone the securedrop-workstation repo to dom0
   - Edit utils/qa-switch.sh to include "sd-large-buster-template" and "sd-small-buster-template" in the list of targets
   - Rhen run `sudo bash utils/qa-switch.sh` to set the yum-test repos
- Confirm that `qvm-ls | grep fedora-32` shows no hits
- Run the GUI updater via `time /opt/securedrop/launcher/sdw-launcher.py --skip-delta=0` and confirm no errors
- In `dom0`, run `qvm-ls | grep fedora-32`, and verify that:
  - [x] `sys-firewall`, `sys-net`, and `sys-usb` are all based on `fedora-32`
  - [x] `sd-app`, `sd-log`, `sd-proxy`, and `sd-gpg` are based on `sd-small-buster-template`
  - [x] `sd-devices-dvm` and `sd-viewer` are based on `sd-large-buster-template`   
- [x] Confirm `qvm-prefs default-mgmt-dvm template` shows `fedora-32`
- [x] Run the graphical updater _again_ to completion, confirm no errors

**Comment by eloquence** [comment]
This was completed last week. During testing, we discovered a regression in the `dom0` update logic that was introduced in 0.5.0 (#646) and fixed via a follow-up release, 0.5.2, issued today.
