### ISSUE TITLE
Update workstation kernels

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#717]
The current prod kernels are 4.14.186-grsec. I recently built 4.14.240-grsec kernels (https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/116) but these fail in VMs on next boot with the error message:

```
cat: can't open '/sys/class/block/xvda/ro`: No such file or directory
sh: 1: unknown operand...
```

I'll compare the configs from 186 & 240 and see if anything obvious is missing, and likely rebuild. 

## Subtasks

- [x] Build new 4.14.x kernel for Workstation, make sure VMs boot on it (4.14.241-grsec-workstation)
- [x] Review and merge kernel-builder tweaks in https://github.com/freedomofpress/kernel-builder/pull/16 (these were used to build)
- [x] Commit old 4.14.186 config to version control (this was a process omission back in 2020-11) - https://github.com/freedomofpress/kernel-builder/pull/16/commits/3b97711e4b2d932153ffa42b38d85ba95d21219f
- [x] Update metapackage for new packages - https://github.com/freedomofpress/securedrop-debian-packaging/pull/259
- [x] Submit dev-lfs PR to add packages to apt-test - https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/120
- [x] Perform clean install on dev and perform functional testing with new kernels
- [x] Update SDW tests with new kernel strings - https://github.com/freedomofpress/securedrop-workstation/pull/718
- [x] Add SDW wiki page how to test candidate kernels - https://github.com/freedomofpress/securedrop-workstation/wiki/Testing-new-kernel-images
- [x] Expand docs in https://github.com/freedomofpress/kernel-builder repo, to make build process more accessible - https://github.com/freedomofpress/kernel-builder/pull/17
- [x] Promote new kernel debs to prod - https://github.com/freedomofpress/securedrop-debian-packages-lfs/pull/60

**Comment by conorsch** [comment]
Still blocked. While reviewing the kernel configs, I discovered that we hadn't version-controlled the most recent config, for 4.14.186, so I've now done that: https://github.com/freedomofpress/kernel-builder/pull/16/commits/3b97711e4b2d932153ffa42b38d85ba95d21219f and will attempt a rebuild on that new basis.

**Comment by conorsch** [comment]
Looks like the latest build on 4.14.241 resolved, once I folded in the config from 186. Will post packages and build logs shortly.

**Comment by conorsch** [comment]
Completed functional testing against our long-running staging instance, and pleased with the results. We still have plenty more testing to do in support of https://github.com/freedomofpress/securedrop-client/issues/1275, but overall I'm so far satisfied with the behavior of the new kernels.

There are a few outstanding PRs related to this epic still up for review. I've gone head and marked the tasks as complete, and will tag the PRs as "closing" this issue once they're reviewed and merged.

**Comment by eloquence** [comment]
Technically, should this issue be closed once the artifacts are promoted to prod?

**Comment by conorsch** [comment]
> should this issue be closed once the artifacts are promoted to prod?

Great point, updated. We've now got one more task on here. =)

**Comment by eloquence** [comment]
I've switched my workstation to `staging` and updated to the new kernels; I've double-checked that AppVMs and DispVMs are using the 241 kernel. 

I've observed no issues during normal use of the workstation and all operations (sync, deletion, replies, export) worked as expected.

**Comment by conorsch** [comment]
>  Promote new kernel debs to prod

Will work on a PR for promotion. I see it as a nice-to-have to ship the RPM changes from https://github.com/freedomofpress/securedrop-workstation/pull/722, specifically those addressing https://github.com/freedomofpress/securedrop-workstation/issues/442, but not worth blocking on.

**Comment by eloquence** [comment]
Looks like this is all done and the new packages are [live](https://apt.freedom.press/pool/main/l/linux-4.14.241-grsec-workstation/). Closing, can open follow-up issues if we encounter any - thanks all for the work on this. :)
