### ISSUE TITLE
Release SecureDrop Workstation 0.5.7

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#737]
We've got a single change we want to ship in a new rpm version, that of migrating the Fedora templates ahead of the current EOL window (#735). Tracking the usual steps related to a release here:

* [x] Review and merge Fedora template changes - #736 
* [x] Bump RPM version to 0.5.7 - #736
* [x] Create signed tag for 0.5.7 - https://github.com/freedomofpress/securedrop-workstation/releases/tag/0.5.7
* [x] Build RPM, sign with test key, submit to dev lfs repo (this is necessary to keep staging in sync even if we don't test separately) - https://github.com/freedomofpress/securedrop-workstation-dev-rpm-packages-lfs/pull/29
* [x] Resign RPM with prod key, submit to prod lfs repo - https://github.com/freedomofpress/securedrop-workstation/issues/737
* [x] Handle pilot comms

Given the extensive testing we've done, I'm fine with submitting PRs to both locations and merging simultaneously. @creviera let me know if you disagree!

**Comment by conorsch** [comment]
Working on this today.

**Comment by conorsch** [comment]
Prod RPM is up and ready for review. Today's Friday, so let's wait till early next week to merge and thereby release.

**Comment by eloquence** [comment]
This was completed via https://github.com/freedomofpress/securedrop-workstation-prod-rpm-packages-lfs/pull/24.
