### ISSUE TITLE
Remove Qubes 4.0-specific code

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-workstation#817]
Remove Qubes-4.0-specific code now that 4.0 is EOL (I'm happy to take this on):

- [ ] Conditional Qubes version checks in Salt states
- [ ] Review Salt states to ensure legacy syntax (`pkg.installed` vs `template.intsalled`) has been removed where appropriate
- [ ] Remove Qt4 code in updater (since f32 supports Qt5)
- [ ] Remove Qt4 in UI tests and CI config
